### ISSUE TITLE
Rename the repo and project files

### ISSUE THREAD

**Issue by rammprasad** [pharmaverse/sdtm.oak#12]
### Background Information

1. [x] Rename the repository to sdtm.oak
2. [x] the package name to sdtm.oak
3. [x] Make the package public
4. [x] Update the description file.

### Definition of Done

Completion of the above tasks

**Comment by ramiromagno** [comment]
The update on the DESCRIPTION is done already: https://github.com/pharmaverse/sdtm.oak/blob/7f1bc0a846376a4e3cd03a325e065b278b736da5/DESCRIPTION#L1.

So I guess we can close this issue.
