### ISSUE TITLE
Documentation:  Template R code

### ISSUE THREAD

**Issue by rammprasad** [pharmaverse/sdtm.oak#17]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

Develop a Vignette to demonstrate how the {sdtm.oak} functions and algorithms can be used to create SDTM domains.

**Comment by joybvictor** [comment]
What library needs to be installed to use the functions read_raw_data_csv, read_sdtm_spec_csv, and read_study_ct_csv. ? I'm quite new to GitHub and not sure if I'm doing it correctly.

**Comment by ramiromagno** [comment]
Hi @joybvictor ,

Those functions are to be understood as pseudocode. Their implementation is actually not provided as of yet. It can nonetheless read the CSV with any CSV importer, e.g. `read.csv()` or `readr::read_csv()`. I hope that helps.

**Comment by joybvictor** [comment]
Understood. I've already loaded the library(readxl), but I want to confirm that I'm on the right path.
