### ISSUE TITLE
Last obs before exposure flag and Baseline Flag

### ISSUE THREAD

**Issue by KoulAshish** [pharmaverse/sdtm.oak#18]
### Feature Idea

Hi All,

Starting from SDTMIG 3.3 a new variable --LOBXL (Last Observation Before Exposure Flag) has been added to finding domains with a view to replace --BLFL (Baseline Flag).

Should we tackle both together or is there a separate thread for --LOBXL.

Source: https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3/html#Observations+and+Variables
Section: 4.5.9

**Comment by MaguluriVenkata** [comment]
I suggest separating both, it's not necessary that both follow identical rule and also maintenance also is easy in future to have a dedicated space.

**Comment by rammprasad** [comment]
@rammprasad to complete the issue description.

**Comment by yli110-stat697** [comment]
> @rammprasad to complete the issue description.

Hi @rammprasad can we define the desired input and output of the function?

**Comment by rammprasad** [comment]
Reference function - https://github.com/pharmaverse/roak_pilot/blob/main/R/oak_derive_blfl.R

**Comment by rammprasad** [comment]
@kamilsi - The function call in {sdtm.oak} can be  oak_derive_blfl(ds_in, der_var, ref_var, ref_dat)

ref_dat will replace the code in the section below https://github.com/pharmaverse/roak_pilot/blob/main/R/oak_derive_blfl.R#L201 to https://github.com/pharmaverse/roak_pilot/blob/main/R/oak_derive_blfl.R#L210

The rest of the derivation logic is almost the same.
