### ISSUE TITLE
Documentation:  <Outstanding items from https://github.com/pharmaverse/sdtm.oak/pull/30>

### ISSUE THREAD

**Issue by edgar-manukyan** [pharmaverse/sdtm.oak#38]
### Let us know where something needs a refresh or put your idea here!

- [x] https://github.com/pharmaverse/sdtm.oak/pull/30#discussion_r1472880301
- [x] https://github.com/pharmaverse/sdtm.oak/pull/30#discussion_r1472925871
- [x] https://github.com/pharmaverse/sdtm.oak/pull/30#discussion_r1473107746
- [x] https://github.com/pharmaverse/sdtm.oak/pull/30#discussion_r1473109951

**Comment by yli110-stat697** [comment]
Hi @edgar-manukyan is this issue resolved now?

**Comment by ramiromagno** [comment]
Hi @edgar-manukyan: I guess this issue can be closed, right?

**Comment by edgar-manukyan** [comment]
It will be fair if @kamilsi tells us since all the above comments are from him. Thanks Kamil.

**Comment by kamilsi** [comment]
Yes, the outstanding comment was to create a dictionary and we have separate issue for that.

**Comment by rammprasad** [comment]
Seems like we are good to close it.
