### ISSUE TITLE
Feature Request:  Implement mapping functions conceptually similar to `assign_no_ct()`/`assign_ct()`

### ISSUE THREAD

**Issue by ramiromagno** [pharmaverse/sdtm.oak#39]
### Feature Idea

As per the example pseudocode provided in the template code: https://github.com/pharmaverse/sdtm.oak/blob/main/inst/cm_domain/create_cm_template.R, implement functionality equivalent to `assign_no_ct()`/`assign_ct()` either as one function, or two, still to be worked out.

### Relevant Input

The relevant input(s) should be:

- The source raw dataset
- The input variable(s) that need to be mapped
- The names of the output variable(s) in the resulting dataset
- An optional parameter taking an object representing the appropriate controlled terminology

### Relevant Output

The output should be a new dataset containing the new variables (as indicated by their names in one of the inputs.

**Comment by rammprasad** [comment]
@ramiromagno - assign_ct() needs controlled terminology as a mandatory parameter.

**Comment by ramiromagno** [comment]
@rammprasad : I was thinking of having one single function, and having that controlled terminology as optional: if provided, then internally run the equivalent of `assign_ct()`, otherwise, default to `assign_no_ct()`.

**Comment by rammprasad** [comment]
if it is ok, lets keep one function per algorithm. It will be easier to maintain in the long run.

**Comment by ramiromagno** [comment]
Hi @rammprasad : could you provide a mock-up example of how the controlled terminology should be used in `assign_ct()`?
