### ISSUE TITLE
First CRAN submission

### ISSUE THREAD

**Issue by ramiromagno** [pharmaverse/sdtm.oak#65]
### Background Information

Issues to be solved before CRAN submission:

- [x] #66 
- [x] #63 
- [x] #58
- [x] #60
- [x] #68 
- [x] #78
- [x] #79
- [x] #81 

### Definition of Done

Package submitted and accepted by CRAN.

**Comment by rammprasad** [comment]
I will perform a last check on documentation to ensure we have everything in place before we approve #77
